/**
 * StepNames - ステップ名の定数定義
 *
 * 型安全なステップ名を提供する。
 * DSLの "activations", "resolutions" セクションで使用する。
 */

export const STEP_NAMES = {
  // ドロー・手札操作関連
  DRAW: "DRAW",
  FILL_HANDS: "FILL_HANDS",
  SELECT_AND_DISCARD: "SELECT_AND_DISCARD",
  SELECT_RETURN_SHUFFLE_DRAW: "SELECT_RETURN_SHUFFLE_DRAW",
  RETURN_ALL_HAND_SHUFFLE_DRAW: "RETURN_ALL_HAND_SHUFFLE_DRAW",
  DISCARD_ALL_HAND_END_PHASE: "DISCARD_ALL_HAND_END_PHASE",

  // サーチ・サルベージ関連
  SEARCH_FROM_DECK: "SEARCH_FROM_DECK",
  SEARCH_FROM_DECK_BY_NAME: "SEARCH_FROM_DECK_BY_NAME",
  SEARCH_FROM_DECK_TOP: "SEARCH_FROM_DECK_TOP",
  SEARCH_MONSTER_BY_STAT: "SEARCH_MONSTER_BY_STAT",
  SALVAGE_FROM_GRAVEYARD: "SALVAGE_FROM_GRAVEYARD",

  // ライフポイント関連
  GAIN_LP: "GAIN_LP",
  PAY_LP: "PAY_LP",
  BURN_DAMAGE: "BURN_DAMAGE",
  BURN_FROM_CONTEXT: "BURN_FROM_CONTEXT",

  // カウンター関連
  PLACE_COUNTER: "PLACE_COUNTER",
  REMOVE_COUNTER: "REMOVE_COUNTER",

  // モンスター関連
  CHANGE_BATTLE_POSITION: "CHANGE_BATTLE_POSITION",
  SPECIAL_SUMMON_FROM_DECK: "SPECIAL_SUMMON_FROM_DECK",
  SPECIAL_SUMMON_FROM_EXTRA_DECK: "SPECIAL_SUMMON_FROM_EXTRA_DECK",
  SPECIAL_SUMMON_FROM_CONTEXT: "SPECIAL_SUMMON_FROM_CONTEXT",
  CREATE_TOKEN_MONSTER: "CREATE_TOKEN_MONSTER",
  EXCAVATE_UNTIL_MONSTER: "EXCAVATE_UNTIL_MONSTER",
  EXCAVATE_UNTIL_MONSTER_WITH_LEVEL_CHECK: "EXCAVATE_UNTIL_MONSTER_WITH_LEVEL_CHECK",

  // 装備操作関連
  ESTABLISH_EQUIP: "ESTABLISH_EQUIP",
  SEND_EQUIPPED_AND_SELF_TO_GRAVEYARD: "SEND_EQUIPPED_AND_SELF_TO_GRAVEYARD",
  UNEQUIP: "UNEQUIP",

  // リリース関連
  RELEASE: "RELEASE",
  RELEASE_FOR_BURN: "RELEASE_FOR_BURN",

  // 除外関連
  SELECT_AND_BANISH_FROM_GRAVEYARD: "SELECT_AND_BANISH_FROM_GRAVEYARD",

  // デッキ操作関連
  SHUFFLE_DECK: "SHUFFLE_DECK",

  // コンテキスト操作関連
  SELECT_TARGET_FROM_FIELD_BY_RACE: "SELECT_TARGET_FROM_FIELD_BY_RACE",
  SELECT_TARGET_FROM_GRAVEYARD: "SELECT_TARGET_FROM_GRAVEYARD",
  SAVE_TARGETS_TO_CONTEXT: "SAVE_TARGETS_TO_CONTEXT",
  CLEAR_CONTEXT: "CLEAR_CONTEXT",
  DECLARE_RANDOM_INTEGER: "DECLARE_RANDOM_INTEGER",

  // その他
  THEN: "THEN",
} as const;

/** 登録済みステップ名の Union 型 */
export type StepName = (typeof STEP_NAMES)[keyof typeof STEP_NAMES];
